### ISSUE TITLE
failed to deduplicate http url versions

### ISSUE THREAD

**Issue by JounQin** [scinos/yarn-deduplicate#124]
![image](https://user-images.githubusercontent.com/8336744/116503062-c28f1200-a8e7-11eb-9ba0-fe5a75131400.png)

```log
eslint-plugin-mdx@^1.12.0:
  version "1.12.0"
  resolved "https://registry.yarnpkg.com/eslint-plugin-mdx/-/eslint-plugin-mdx-1.12.0.tgz#7d8a722eb6cd97f3d81aa02fb3430f5fe17c1797"
  integrity sha512-d+vmIyyoDvRjQ0XGZ1v9DtnEk79dUOK+LzHoDGlBvtQHjlMyHl54Mw4EblX3d3nysyLss3+1V0SOrj+e9F+lNQ==
  dependencies:
    cosmiconfig "^7.0.0"
    eslint-mdx "^1.12.0"
    remark-mdx "^1.6.22"
    remark-parse "^8.0.3"
    remark-stringify "^8.1.1"
    tslib "^2.1.0"
    unified "^9.2.1"
    vfile "^4.2.1"

"eslint-plugin-mdx@https://pkg.csb.dev/mdx-js/eslint-mdx/commit/6a3b2aa4/eslint-plugin-mdx":
  version "1.12.0"
  resolved "https://pkg.csb.dev/mdx-js/eslint-mdx/commit/6a3b2aa4/eslint-plugin-mdx#3e16a11e9ae1231d374ff3c60c0dc6af3dcbb09a"
  dependencies:
    cosmiconfig "^7.0.0"
    eslint-mdx "https://pkg.csb.dev/mdx-js/eslint-mdx/commit/6a3b2aa4/eslint-mdx"
    eslint-plugin-markdown "^2.1.0"
    remark-mdx "^1.6.22"
    remark-parse "^8.0.3"
    remark-stringify "^8.1.1"
    synckit "^0.1.5"
    tslib "^2.2.0"
    unified "^9.2.1"
    vfile "^4.2.1"
```

`"eslint-plugin-mdx": "https://pkg.csb.dev/mdx-js/eslint-mdx/commit/6a3b2aa4/eslint-plugin-mdx"` is used in `package.json`, and the normal one is installed by a (dev) dependency.

It should consider dep in `package.json` with higher priority, and deduplicate them.

**Comment by scinos** [comment]
I didn't know you can use an url as the version specifier. 

I'll try to have a look to see what can we do about it, but my initial reaction is that this is not possible: there is no way to know that `https://pkg.csb.dev/mdx-js/eslint-mdx/commit/6a3b2aa4/eslint-plugin-mdx` can (and will always) be satisfied by the same version used for `eslint-plugin-mdx@^1.12.0`, no?

**Comment by scinos** [comment]
Yeah, I don't see how we can do this.

`https://pkg.csb.dev/mdx-js/eslint-mdx/commit/6a3b2aa4/eslint-plugin-mdx` is not a range but a specific version, so there is no easy way we can determine it overlaps with `^1.12.0` and deduplicate it.
