### ISSUE TITLE
Give a friendlier message for --fail --list

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [scinos/yarn-deduplicate#133]
Thanks for setting up this great library!

Here's an example in CI of a failure:

```
$ yarn-deduplicate --fail --list
Package "@assemblyscript/loader" wants ^0.10.1 and could get 0.10.2, but got 0.10.1
error Command failed with exit code 1.
```

The error message doesn't indicate what someone should do to resolve it (`npx deduplicate`). Would you accept a PR that adds a friendly message if `--fail` and `--list` are provided?

```
$ yarn-deduplicate --fail --list
Package "@assemblyscript/loader" wants ^0.10.1 and could get 0.10.2, but got 0.10.1
Run `npx yarn-deduplicate` to deduplicate yarn.lock entries
error Command failed with exit code 1.
```

**Comment by scinos** [comment]
Hi! Sorry for the (massive) delay.

Couldn't be this solved at the shell level? `yarn-deduplicate --fail --list || echo "Run `npx yarn-deduplicate` to deduplicate yarn.lock entries"`.

I rather not tell the user how to run `yarn-deduplicate`. They may be using `npx`, or `npm run yarn-deduplicate`, or `yarn run yarn-deduplicate`...

**Comment by JoshuaKGoldberg** [comment]
Those are good points: yes, this could be solved at the user-level, and with various different installers the users might use.

But:
* Adding the `|| echo "..."` line to a `package.json` or CI script is a bit of extra and unwieldy work
* Standardizing the message means teams that don't think to add this to CI get it for free

Avoiding the specifics of which tool, how about...

```
Run yarn-deduplicate to deduplicate yarn.lock entries.
```

I'd be happy to send this in as a PR!
