### ISSUE TITLE
Error: unknown option '--exclude-scopes'

### ISSUE THREAD

**Issue by s7s7s7** [scinos/yarn-deduplicate#144]
Helllo yar-deduplicate team. I am using the `yarn-deduplicate@3.1.0`. I noticed that in the Readme doc there is an option `--exclude-scopes`. However, when I try to use this option, I got `error: unknown options '--exclude-scopes'`. And this is what I got if I run `--help`: 

![image](https://user-images.githubusercontent.com/29487160/160911093-9372c362-385c-44c2-a73c-bf6dbc0f10e5.png)

It seems this option has been removed/not implemented yet.

I am wondering is that possible to add this option? It seems very useful in some cases, especially if we want to run the yarn-deduplicate every time before merging a PR.

Also thank you very much for this great project.

**Comment by scinos** [comment]
`--exclude-scopes` have been implemented in v4.0.0

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/975703/163668262-4ee136cd-31ba-4aac-a5ba-84c428a1f2a2.png">
