### ISSUE TITLE
yarn-deduplicate: command not found

### ISSUE THREAD

**Issue by KVPasupuleti** [scinos/yarn-deduplicate#145]
Node version : 15.14.0
Yarn version : 1.22.5

I have duplicates in my yarn.lock file

I have installed yarn-deduplicate using

```
yarn global add yarn-deduplicate
```

But, when running the command `yarn-deduplicate`,

I am getting this 

![image](https://user-images.githubusercontent.com/36617018/163596918-4df90957-638c-461d-b1ae-367d06fc0233.png)

**Comment by scinos** [comment]
Sounds like yarn global path is not part of your $PATH.

I'd suggest to have a look at Yarn docs: https://classic.yarnpkg.com/en/docs/cli/global#adding-the-install-location-to-your-path
