### ISSUE TITLE
Lower tslib dependency

### ISSUE THREAD

**Issue by glensc** [scinos/yarn-deduplicate#194]
Could you lower `tslib "^2.4.0"` to `tslib@^2`, so (ironically) adding `yarn-deduplicate` to `yarn.lock` wouldn't add another entry to `yarn.lock` because some packages have `tslib@~2.0.1` dependency:

```
✖  grep ^tslib yarn.lock
tslib@^1, tslib@^1.10.0, tslib@^1.8.1, tslib@^1.9.0, tslib@^1.9.3:
tslib@^2, tslib@^2.0.0, tslib@^2.0.1, tslib@^2.0.3, tslib@^2.1.0, tslib@^2.4.0:
tslib@~2.0.1:
tslib@~2.1.0:
tslib@~2.2.0:
tslib@~2.3.0:
```

**Comment by glensc** [comment]
It was bumped by dependabot:
- https://github.com/scinos/yarn-deduplicate/commit/fcfee18fa51af03b7a08cd8aaa750ce5686f8796

**Comment by scinos** [comment]
Using `tslib@^2` would mean it would be ok for this project to use `tslib 2.0.0`, which is not compatible (according to their [release notes](https://github.com/microsoft/tslib/releases)) to latest TypeScript, so I would need to downgrade TypeScript too. Is not a change I'm eager to make unless there is a very strong reason.

May I suggest you use [resolutions](https://classic.yarnpkg.com/en/docs/package-json#toc-resolutions) to force those packages (packages that depend on `tslib@~2.0.1`) to depend on `tslib@^2` instead?

**Comment by glensc** [comment]
This was just an idea, the tslib duplicates aren't that big, so it's not a major issue.
