### ISSUE TITLE
Not aggregating when specific "version" property is differently setted

### ISSUE THREAD

**Issue by marco-carvalho** [scinos/yarn-deduplicate#227]
Let's say I have this `yarn.lock`:
```
schema-utils@^3.0.0:
  version "3.0.0"

schema-utils@^3.1.0:
  version "3.1.0"

schema-utils@^3.1.1:
  version "3.1.1"
```

If I use `yarn-deduplicate`, it returns `schema-utils@^3.0.0, schema-utils@^3.1.0, schema-utils@^3.1.1:`, which is exactly what I wanted.

Now let's say I have this `yarn.lock`:
```
schema-utils@^3.0.0:
  version "3.1.1"

schema-utils@^3.1.0:
  version "3.1.1"

schema-utils@^3.1.1:
  version "3.1.1"
```

If I use `yarn-deduplicate`, it doesn't returns `schema-utils@^3.0.0, schema-utils@^3.1.0, schema-utils@^3.1.1:`, but I thought it should return it. Did I understand it incorrectly?

**Comment by marco-carvalho** [comment]
I created https://github.com/scinos/yarn-deduplicate/pull/228 to showcase this problem.

**Comment by scinos** [comment]
How do you generate that lock file in the first place?

I've never seen that case (two separate entries with the same version and other properties) so I assume yarn itself  will avoid that situation. But maybe I'm wrong?

**Comment by marco-carvalho** [comment]
This happened in a React project inside my job. After I executed `yarn install`, it resolved correctly.
