### ISSUE TITLE
Running `yarn install` after `yarn-tools fix-duplicates` sometimes changes the `yarn.lock` file

### ISSUE THREAD

**Issue by scinos** [scinos/yarn-deduplicate#5]
*Originally reported by* **Ruslan Arkhipau (Bitbucket: [rarkhipau-at-atlassian](https://bitbucket.org/rarkhipau-at-atlassian), GitHub: Unknown)**

----------------------------------------

Essentially this boils down to: "Whatever the `fix-duplicates` command is doing can get out of sync with what yarn itself is doing". 

It might be worth to add a line to readme saying "after updating the lock file with `yarn-tools fix-duplicates`, make sure to run the `yarn install` command"

----------------------------------------
- Bitbucket: https://bitbucket.org/atlassian/yarn-tools/issue/5

**Comment by scinos** [comment]
In case someone wants to try a PR to fix this:

My theory is that after removing duplicates, there are orphan packages left in the lock file. It should be "easy" to fix by walking the tree and removing those packages that has no parent.

**Comment by mockdeep** [comment]
Would it be worth letting `yarn` do this instead by running `yarn install` again after deduplicating?
