### ISSUE TITLE
Diagnosis for dependencies with non-overlapping versions

### ISSUE THREAD

**Issue by graup** [scinos/yarn-deduplicate#66]
The readme states, "it is important to note that we do not consider duplicated packages when the version ranges don't overlap."

However, diagnosis of this would be a useful feature. In big open-source monorepos, over time a lot of duplicate dependencies accumulate. Having a list of those, to then manually check and de-duplicate, would be great!

**Comment by scinos** [comment]
I think that's a bit outside the scope of this package.

That being said, it's a good idea and I'm not aware of any tool to get that information. Maybe it's time to write a different tool!
